"""Phase 3: confident misses, judge styles, pre- vs post-2017 scoring.

Uses 2017-2023 (train + tune) for the post-2017 analyses. Test (2024+) is not
touched. Judge results will be extended to 2024+ only after the final test
evaluation, so nothing seen here can leak into model choices.

Writes reports/phase3_analysis.md and reports/tape_review.csv.
The judge-name mapping goes to data/processed/judge_key.csv (gitignored).
"""
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from ufcj.load import load  # noqa: E402
from ufcj.splits import assign_time_split  # noqa: E402
from ufcj.evaluate import require_test_unlock  # noqa: E402
from ufcj.features import FEATURES, UNITS, round_features  # noqa: E402
from ufcj.model import Prepared, fit, card_predictions, weights_table, unpack, round_win_prob  # noqa: E402
from ufcj.judges import fit_judge, lr_pvalue, benjamini_hochberg, anonymize  # noqa: E402

N_BOOT = int(sys.argv[1]) if len(sys.argv) > 1 else 100
rng = np.random.default_rng(3)

t = load()
fights, cards, rounds = t["fights"], t["cards"], t["rounds"]
fights["split"] = assign_time_split(fights)
for s in ["train", "tune", "pre2017"]:
    require_test_unlock(s)
post = fights[fights.split.isin(["train", "tune"])].copy()
c_post, r_post = cards[cards.fid.isin(post.fid)], rounds[rounds.fid.isin(post.fid)]

L = ["# Phase 3: what the model misses, judge styles, and the 2017 rule change", "",
     "Post-2017 analyses use 2017–2023 fights (train + tune). Test set (2024+) not touched.",
     "Generated by `scripts/run_phase3.py`.", ""]

# =====================================================================
# 1. Confident misses (cross-fitted so every prediction is out-of-sample)
# =====================================================================
fids = post.fid.to_numpy()
fold = pd.Series(rng.integers(0, 5, len(fids)), index=fids)
preds, round_p = [], []
for k in range(5):
    tr_f, te_f = fold.index[fold != k], fold.index[fold == k]
    p_tr = Prepared(c_post[c_post.fid.isin(tr_f)], r_post[r_post.fid.isin(tr_f)])
    params_k = fit(p_tr)
    p_te = Prepared(c_post[c_post.fid.isin(te_f)], r_post[r_post.fid.isin(te_f)], scale=p_tr.scale)
    preds.append(card_predictions(p_te, params_k))
    w, _, _ = unpack(params_k)
    contrib = pd.DataFrame(p_te.X * w, columns=FEATURES)
    contrib[["fid", "rnd"]] = p_te.rounds[["fid", "rnd"]].to_numpy()
    contrib["p_round"] = round_win_prob(p_te, params_k)
    round_p.append(contrib)
pred = pd.concat(preds).set_index("fid")
rp = pd.concat(round_p)

judge_side = cards[cards.fid.isin(post.fid)].assign(s=lambda d: np.sign(d.A_pts - d.B_pts)).groupby("fid").s
unan = judge_side.agg(lambda s: s.iloc[0] if (s == s.iloc[0]).all() and s.iloc[0] != 0 else 0)
pred["judges"] = unan
pred["fav"] = np.where(pred.p_A_ahead >= 0.5, 1, -1)
pred["conf"] = np.maximum(pred.p_A_ahead, 1 - pred.p_A_ahead)
u = pred[pred.judges != 0]
miss = u[(u.conf >= 0.8) & (u.fav != u.judges)]
hit = u[(u.conf >= 0.8) & (u.fav == u.judges)]

L += ["## 1. Confident misses", "",
      "Every fight gets an out-of-sample prediction (5-fold cross-fitting on 2017–23). A confident miss is a "
      "fight where the model gave one fighter at least an 80% chance of being ahead on a card, and all three "
      "judges had the other fighter ahead.", "",
      f"- Fights with a unanimous direction across judges: {len(u)}",
      f"- Model at least 80% confident: {len(miss) + len(hit)} "
      f"({(len(miss) + len(hit)) / len(u):.0%} of those fights)",
      f"- Confident and wrong against all three judges: **{len(miss)}** "
      f"({len(miss) / (len(miss) + len(hit)):.1%} of confident calls)", ""]

# What drove the model's (wrong) confidence? Sum each feature's contribution toward the favoured fighter.
fight_contrib = rp.groupby("fid")[FEATURES].sum()


def driver_mix(fid_index, fav):
    fc = fight_contrib.loc[fid_index].mul(fav.loc[fid_index], axis=0)
    striking = fc[["dist", "clinch", "ground", "sig_missed", "nonsig", "kd"]].sum(axis=1)
    grappling = fc[["td", "td_failed", "sub", "rev", "ctrl_min"]].sum(axis=1)
    share = grappling.clip(lower=0) / (striking.clip(lower=0) + grappling.clip(lower=0))
    return share


g_miss, g_hit = driver_mix(miss.index, miss.fav), driver_mix(hit.index, hit.fav)
ctrl_miss = (fight_contrib.loc[miss.index, "ctrl_min"] * miss.fav).gt(0).mean()
ctrl_hit = (fight_contrib.loc[hit.index, "ctrl_min"] * hit.fav).gt(0).mean()
diff_boot = []
for _ in range(2000):
    a = rng.choice(g_miss.to_numpy(), len(g_miss))
    b = rng.choice(g_hit.to_numpy(), len(g_hit))
    diff_boot.append(np.nanmean(a) - np.nanmean(b))
lo, hi = np.percentile(diff_boot, [2.5, 97.5])
L += ["**What the model leaned on.** For each fight, the share of the model's case for the favoured fighter "
      "that came from grappling (takedowns, control, submissions, reversals) rather than striking:", "",
      f"- Confident misses: {g_miss.mean():.0%} grappling",
      f"- Confident hits: {g_hit.mean():.0%} grappling",
      f"- Difference: {g_miss.mean() - g_hit.mean():+.0%} [95% CI {lo:+.0%}, {hi:+.0%}]",
      f"- Favoured fighter also had more total control time: misses {ctrl_miss:.0%}, hits {ctrl_hit:.0%}", ""]

# tape-review sheet: the round in each missed fight the model was most confident the favoured fighter won
fmeta = fights.set_index("fid")
rows = []
for fid, m in miss.sort_values("conf", ascending=False).iterrows():
    r = rp[rp.fid == fid].copy()
    r["p_fav"] = np.where(m.fav == 1, r.p_round, 1 - r.p_round)
    f = fmeta.loc[fid]
    fav_name = f.A if m.fav == 1 else f.B
    raw = rounds[rounds.fid == fid].set_index("rnd")
    for _, rr in r.sort_values("p_fav", ascending=False).head(2).iterrows():
        rnd = int(rr.rnd)
        s_f = "A" if m.fav == 1 else "B"
        s_o = "B" if m.fav == 1 else "A"
        x = raw.loc[rnd]
        rows.append({
            "date": f.date.date(), "event": f.event, "bout": f.bout, "model_favoured": fav_name,
            "model_conf": round(m.conf, 3), "round": rnd, "p_fav_won_round": round(rr.p_fav, 3),
            "sig_landed_fav_opp": f"{int(x[f'sig_{s_f}'])}-{int(x[f'sig_{s_o}'])}",
            "kd_fav_opp": f"{int(x[f'kd_{s_f}'])}-{int(x[f'kd_{s_o}'])}",
            "td_fav_opp": f"{int(x[f'td_{s_f}'])}-{int(x[f'td_{s_o}'])}",
            "ctrl_sec_fav_opp": f"{int(x[f'ctrl_{s_f}'])}-{int(x[f'ctrl_{s_o}'])}",
            "what_the_stats_missed": "", "category": "", "notes": "",
        })
tape = pd.DataFrame(rows)
# Full sheet with per-round stat lines stays local (data/processed is gitignored).
# The public report omits the UFCStats stat columns; see README "Data and terms of use".
tape.to_csv(ROOT / "data" / "processed" / "tape_review_with_stats.csv", index=False)
stat_cols = ["sig_landed_fav_opp", "kd_fav_opp", "td_fav_opp", "ctrl_sec_fav_opp",
             "what_the_stats_missed", "category", "notes"]
tape.drop(columns=stat_cols).to_csv(ROOT / "reports" / "tape_review.csv", index=False)
L += [f"**Tape review sheet:** `reports/tape_review.csv` (stat lines kept local in data/processed) lists the {len(miss)} missed fights, with the two rounds "
      "per fight the model was most sure the favoured fighter won (at least one of them must have gone the other "
      "way on every card). Suggested categories: *damage not in the stats*, *late-round surge*, "
      "*control without offense*, *stat recording error*, *questionable scoring*, *other*.", "",
      "Top 10 by model confidence:", "",
      tape.drop_duplicates("bout").head(10)[["date", "bout", "model_favoured", "model_conf"]].to_markdown(index=False), ""]

# =====================================================================
# 2. Judge styles
# =====================================================================
prep_all = Prepared(c_post, r_post)
gparams = fit(prep_all)
_, t1g, t2g = unpack(gparams)
vc = c_post.judge.value_counts()
judges = [j for j in vc[vc >= 100].index if j != "UNKNOWN"]
key = anonymize(judges)
pd.Series(key, name="label").rename_axis("judge").to_csv(ROOT / "data" / "processed" / "judge_key.csv")

c_maj = c_post.assign(s=np.sign(c_post.A_pts - c_post.B_pts))
c_maj["fight_major"] = c_maj.groupby("fid").s.transform(lambda s: np.sign(s.sum()))
rows = []
for j in judges:
    cj = c_post[c_post.judge == j]
    pj = Prepared(cj, r_post[r_post.fid.isin(cj.fid)], scale=prep_all.scale)
    dev, ll1, ll0 = fit_judge(pj, gparams)
    boots = []
    jf = cj.fid.unique()
    cj_by = {f: g for f, g in cj.groupby("fid")}
    rj_by = {f: g for f, g in r_post[r_post.fid.isin(jf)].groupby("fid")}
    for b in range(N_BOOT):
        pick = pd.Series(rng.choice(jf, len(jf))).value_counts()
        cb = pd.concat([cj_by[f].assign(fid=f"{f}_{k}") for f, n in pick.items() for k in range(n)])
        rb = pd.concat([rj_by[f].assign(fid=f"{f}_{k}") for f, n in pick.items() for k in range(n)])
        boots.append(fit_judge(Prepared(cb, rb, scale=prep_all.scale), gparams)[0])
    boots = np.array(boots)
    mj = c_maj[c_maj.judge == j]
    rows.append({
        "judge": key[j], "cards": len(cj),
        "striking": dev[0], "s_lo": np.percentile(boots[:, 0], 2.5), "s_hi": np.percentile(boots[:, 0], 97.5),
        "grappling": dev[1], "g_lo": np.percentile(boots[:, 1], 2.5), "g_hi": np.percentile(boots[:, 1], 97.5),
        "t108": dev[2], "c_lo": np.percentile(boots[:, 2], 2.5), "c_hi": np.percentile(boots[:, 2], 97.5),
        "tilt": (1 + dev[1]) / (1 + dev[0]) - 1,
        "t_lo": np.percentile((1 + boots[:, 1]) / (1 + boots[:, 0]) - 1, 2.5),
        "t_hi": np.percentile((1 + boots[:, 1]) / (1 + boots[:, 0]) - 1, 97.5),
        "p": lr_pvalue(ll1, ll0),
        "rate_10_8": (cj.dev < 0).mean(),
        "dissent": (mj.s != mj.fight_major).mean(),
    })
    print("judge done", key[j])
J = pd.DataFrame(rows)
J["q"] = benjamini_hochberg(J.p.to_numpy())
J = J.sort_values("judge")


def ci(v, lo, hi, pct=True):
    f = (lambda x: f"{x:+.0%}") if pct else (lambda x: f"{x:+.2f}")
    flag = " *" if (lo > 0 or hi < 0) else ""
    return f"{f(v)} [{f(lo)}, {f(hi)}]{flag}"


show = pd.DataFrame({
    "judge": J.judge, "cards": J.cards,
    "striking weight vs avg": [ci(*x) for x in zip(J.striking, J.s_lo, J.s_hi)],
    "grappling weight vs avg": [ci(*x) for x in zip(J.grappling, J.g_lo, J.g_hi)],
    "grappling tilt": [ci(*x) for x in zip(J.tilt, J.t_lo, J.t_hi)],
    "10-8 strictness": [ci(*x, pct=False) for x in zip(J.t108, J.c_lo, J.c_hi)],
    "10-8 card rate": J.rate_10_8.map("{:.1%}".format),
    "dissents from majority": J.dissent.map("{:.1%}".format),
    "differs from avg? (BH q)": J.q.map(lambda q: f"{q:.3f}" + (" **" if q < 0.05 else "")),
}).reset_index(drop=True)
L += ["## 2. Judge styles (anonymized)", "",
      f"Judges with at least 100 cards in 2017–23: {len(judges)} (covering {vc[judges].sum()} of {len(c_post)} cards). "
      "Each judge is compared against the shared model fit on all 2017–23 cards, holding the stats fixed, so "
      "the comparison is always \"same rounds, different judge\". Deviations are shrunk toward zero.", "",
      "- **Striking / grappling weight vs avg:** +20% means this judge's cards respond 20% more strongly to that "
      "half of the stat line than the average judge's do.",
      "- **Grappling tilt:** grappling weight relative to striking weight for this judge. Positive = favours "
      "grapplers relative to the average judge, separately from how closely the judge tracks the stats overall. "
      "When both weights are above zero, the judge's cards simply follow the recorded stats more closely than "
      "average (fewer surprises), which is a different thing from a style preference.",
      "- **10-8 strictness:** log-scale shift in the 10-8 threshold. Positive = needs a more dominant round.",
      "- `*` = 95% bootstrap interval excludes zero. `**` = the judge's overall style differs from average after "
      f"correcting for testing {len(judges)} judges (Benjamini–Hochberg q < 0.05).", "",
      show.to_markdown(index=False), "",
      f"Shared model thresholds for reference: t2 = {t2g:.2f}.", ""]

# =====================================================================
# 3. Pre-2017 vs post-2017
# =====================================================================
pre = fights[(fights.split == "pre2017") & (fights.year >= 2011)]
tr = fights[fights.split == "train"]
sets = {"2011–2016": pre.fid, "2017–2021": tr.fid}
prep_ref = Prepared(cards[cards.fid.isin(tr.fid)], rounds[rounds.fid.isin(tr.fid)])
scale = prep_ref.scale
est, bts = {}, {}
for name, f in sets.items():
    cs, rs = cards[cards.fid.isin(f)], rounds[rounds.fid.isin(f)]
    p0 = Prepared(cs, rs, scale=scale)
    params = fit(p0)
    est[name] = weights_table(params, scale).per_unit
    c_by = {k: g for k, g in cs.groupby("fid")}
    r_by = {k: g for k, g in rs.groupby("fid")}
    ids = cs.fid.unique()
    out = []
    for b in range(N_BOOT):
        pick = pd.Series(rng.choice(ids, len(ids))).value_counts()
        cb = pd.concat([c_by[k].assign(fid=f"{k}_{i}") for k, n in pick.items() for i in range(n)])
        rb = pd.concat([r_by[k].assign(fid=f"{k}_{i}") for k, n in pick.items() for i in range(n)])
        out.append(weights_table(fit(Prepared(cb, rb, scale=scale), x0=params), scale).per_unit.to_numpy())
        print(f"{name} boot {b + 1}/{N_BOOT}", end="\r")
    bts[name] = np.array(out)

d_idx = FEATURES.index("dist")
rows = []
for i, feat in enumerate(FEATURES):
    ex = {n: bts[n][:, i] / bts[n][:, d_idx] for n in sets}
    pt = {n: est[n].iloc[i] / est[n].iloc[d_idx] for n in sets}
    diff = ex["2017–2021"] - ex["2011–2016"]
    lo, hi = np.percentile(diff, [2.5, 97.5])
    rows.append({
        "stat": UNITS[feat],
        "2011–2016": f"{pt['2011–2016']:.1f} [{np.percentile(ex['2011–2016'], 2.5):.1f}, {np.percentile(ex['2011–2016'], 97.5):.1f}]",
        "2017–2021": f"{pt['2017–2021']:.1f} [{np.percentile(ex['2017–2021'], 2.5):.1f}, {np.percentile(ex['2017–2021'], 97.5):.1f}]",
        "change": f"{pt['2017–2021'] - pt['2011–2016']:+.1f} [{lo:+.1f}, {hi:+.1f}]" + (" *" if lo > 0 or hi < 0 else ""),
    })
cmp_ = pd.DataFrame(rows)
L += ["## 3. Before and after the 2017 criteria rewrite", "",
      f"Same model fit separately on 2011–2016 ({len(pre)} fights) and 2017–2021 ({len(tr)} fights). Values are "
      "exchange rates in landed distance strikes, with 95% bootstrap intervals. `*` = the change excludes zero.", "",
      cmp_.to_markdown(index=False), "",
      "Caveat: the rules changed at different times in different states during 2017, and stat-recording "
      "practices may also have shifted over the decade, so a change here is consistent with, not proof of, "
      "a rule effect.", ""]

out = ROOT / "reports" / "phase3_analysis.md"
out.write_text("\n".join(L))
print("\n".join(L))
