"""Phase 2: fit the round-scoring model on train (2017-21), evaluate on tune (2022-23).

Never touches test. Writes reports/phase2_model.md.
Takes a few minutes because of the bootstrap.
"""
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from ufcj.load import load  # noqa: E402
from ufcj.splits import assign_time_split, grouped_random_split  # noqa: E402
from ufcj.evaluate import card_scores, summarize, ceiling_scores, require_test_unlock  # noqa: E402
from ufcj.baselines import BASELINES  # noqa: E402
from ufcj.features import FEATURES, UNITS  # noqa: E402
from ufcj.model import Prepared, fit, round_win_prob, card_predictions, weights_table, unpack  # noqa: E402

N_BOOT = int(sys.argv[1]) if len(sys.argv) > 1 else 100
rng = np.random.default_rng(0)

t = load()
fights, cards, rounds = t["fights"], t["cards"], t["rounds"]
fights["split"] = assign_time_split(fights)
fights["drift_split"] = grouped_random_split(fights)


def subset(split_col, name):
    require_test_unlock(name)
    f = fights[fights[split_col] == name].fid
    return cards[cards.fid.isin(f)], rounds[rounds.fid.isin(f)]


def fmt(s):
    return s.apply(lambda x: f"{x['mean']:.3f} [{x['lo']:.3f}, {x['hi']:.3f}]", axis=1)


L = ["# Phase 2: round-scoring model", "",
     "Fit on train (2017–21), evaluated on tune (2022–23). Test set not touched.",
     "Generated by `scripts/run_phase2.py`.", ""]

# ---------------------------------------------------------------- fit
c_tr, r_tr = subset("split", "train")
prep_tr = Prepared(c_tr, r_tr)
params = fit(prep_tr)
w, t1, t2 = unpack(params)
L += [f"Training cards: {len(prep_tr.cards)} (skipped as unmodelable: {prep_tr.n_skipped}).",
      f"Fitted thresholds: t1 = {t1:.4f}, t2 = {t2:.2f}. A t1 near zero means the model has learned "
      "that 10-10 rounds almost never happen; t2 sets how dominant a round must be for a 10-8.", ""]

# ---------------------------------------------------------------- tune metrics
c_tu, r_tu = subset("split", "tune")
prep_tu = Prepared(c_tu, r_tu, scale=prep_tr.scale)
rows = []
for name, rule in BASELINES.items():
    s = summarize(card_scores(c_tu, prep_tu.rounds, rule(prep_tu.rounds)))
    s.insert(0, "method", name)
    rows.append(s)
s = summarize(card_scores(c_tu, prep_tu.rounds, round_win_prob(prep_tu, params)))
s.insert(0, "method", "MODEL")
rows.append(s)
s = summarize(ceiling_scores(c_tu))
s.insert(0, "method", "CEILING")
rows.append(s)
tab = pd.concat(rows)
tab = tab[tab.metric != "round_count_ll"].assign(result=lambda d: fmt(d))
wide = tab.pivot(index="method", columns="metric", values="result").loc[
    list(BASELINES) + ["MODEL", "CEILING"]]
L += ["## Tune-set results (locked metrics, 95% fight-bootstrap CI)", "", wide.to_markdown(), ""]

# exact card (model-native; uses every card including 10-8s)
pred = card_predictions(prep_tu, params).set_index("fid")
cc = c_tu.join(pred, on="fid")
exact = ((cc.top_A == cc.A_pts) & (cc.top_B == cc.B_pts)).mean()
modal = c_tu.groupby("fid").apply(lambda g: g.groupby(["A_pts", "B_pts"]).size().max() / len(g), include_groups=False)
L += [f"Exact card score (all {len(cc)} tune cards, including 10-8s): model {exact:.3f}, "
      f"ceiling {modal.mean():.3f}.", ""]

# ---------------------------------------------------------------- calibration
cc = cc[cc.A_pts != cc.B_pts].copy()
cc["y"] = (cc.A_pts > cc.B_pts).astype(int)
cc["bin"] = pd.cut(cc.p_A_ahead, np.linspace(0, 1, 11), include_lowest=True)
cal = cc.groupby("bin", observed=True).agg(cards=("y", "size"), predicted=("p_A_ahead", "mean"), observed=("y", "mean"))
ece = (cal.cards * (cal.predicted - cal.observed).abs()).sum() / cal.cards.sum()
L += ["## Calibration on tune (does 70% mean 70%?)", "",
      "P(judge has fighter A ahead), grouped into ten bins.", "",
      cal.round(3).to_markdown(), "", f"Expected calibration error: {ece:.3f}", ""]

# ---------------------------------------------------------------- drift diagnostic
c_dtr, r_dtr = subset("drift_split", "train")
c_dtu, r_dtu = subset("drift_split", "tune")
p_d = Prepared(c_dtr, r_dtr)
params_d = fit(p_d)
p_dtu = Prepared(c_dtu, r_dtu, scale=p_d.scale)
sd = summarize(card_scores(c_dtu, p_dtu.rounds, round_win_prob(p_dtu, params_d)))
st = summarize(card_scores(c_tu, prep_tu.rounds, round_win_prob(prep_tu, params)))
drift = pd.DataFrame({"time split (train 17-21, tune 22-23)": fmt(st).values,
                      "random split, fights kept whole": fmt(sd).values}, index=st.metric)
L += ["## Drift check", "",
      "Same model, two ways of splitting. If scoring changed over time, the random split "
      "(which mixes years) should look noticeably better than the time split.", "",
      drift.loc[["card_winner_acc", "round_count_acc"]].to_markdown(), ""]

# ---------------------------------------------------------------- weights + bootstrap
fids = c_tr.fid.unique()
c_by = {f: g for f, g in c_tr.groupby("fid")}
r_by = {f: g for f, g in r_tr.groupby("fid")}
boots = []
for b in range(N_BOOT):
    pick = rng.choice(fids, len(fids), replace=True)
    counts = pd.Series(pick).value_counts()
    cb = pd.concat([c_by[f].assign(fid=f"{f}_{k}") for f, n in counts.items() for k in range(n)])
    rb = pd.concat([r_by[f].assign(fid=f"{f}_{k}") for f, n in counts.items() for k in range(n)])
    pb = Prepared(cb, rb, scale=prep_tr.scale)
    boots.append(weights_table(fit(pb, x0=params), prep_tr.scale).per_unit.to_numpy())
    print(f"bootstrap {b + 1}/{N_BOOT}", end="\r")
boots = np.array(boots)

wt = weights_table(params, prep_tr.scale)
ref = wt.loc["dist", "per_unit"]
wt["lo"], wt["hi"] = np.percentile(boots, 2.5, axis=0), np.percentile(boots, 97.5, axis=0)
ex = boots / boots[:, [FEATURES.index("dist")]]
wt["= distance strikes"] = wt.per_unit / ref
wt["ds_lo"], wt["ds_hi"] = np.percentile(ex, 2.5, axis=0), np.percentile(ex, 97.5, axis=0)
wt.index = [UNITS[f] for f in wt.index]
show = pd.DataFrame({
    "log-odds per unit [95% CI]": wt.apply(lambda x: f"{x.per_unit:+.3f} [{x.lo:+.3f}, {x.hi:+.3f}]", axis=1),
    "worth this many distance strikes [95% CI]": wt.apply(
        lambda x: f"{x['= distance strikes']:.1f} [{x.ds_lo:.1f}, {x.ds_hi:.1f}]", axis=1),
    "per SD (relative importance)": wt.per_sd.round(2),
}).sort_values("per SD (relative importance)", ascending=False)
L += ["## What the model says judges reward (fit on 2017–21)", "",
      f"Bootstrap: {N_BOOT} refits, resampling fights. 'Worth this many distance strikes' is the "
      "exchange rate: how many extra landed distance strikes move the round the same amount.", "",
      show.to_markdown(), "",
      "Read with care: control time and ground strikes happen together, so their weights share credit. "
      "These describe what predicts judges' cards from recorded stats, which is not the same as what judges "
      "consciously score.", ""]

# ---------------------------------------------------------------- sensitivity: 10-9 cards only
c_109 = c_tr[c_tr.dev == 0]
p109 = Prepared(c_109, r_tr[r_tr.fid.isin(c_109.fid)], scale=prep_tr.scale)
w109 = weights_table(fit(p109), prep_tr.scale).per_unit
sens = pd.DataFrame({"all cards": weights_table(params, prep_tr.scale).per_unit, "10-9 cards only": w109})
sens.index = [UNITS[f] for f in sens.index]
L += ["## Sensitivity: what dropping 10-8/10-10 cards would have done", "",
      sens.round(3).to_markdown(), ""]

out = ROOT / "reports" / "phase2_model.md"
out.write_text("\n".join(L))
print("\n".join(L))
