"""Phase 1: baselines and ceilings on train and tune. Never touches test."""
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from ufcj.load import load  # noqa: E402
from ufcj.splits import assign_time_split, grouped_random_split  # noqa: E402
from ufcj.evaluate import card_scores, summarize, ceiling_scores, require_test_unlock  # noqa: E402
from ufcj.baselines import BASELINES  # noqa: E402

t = load()
fights, cards, rounds = t["fights"], t["cards"], t["rounds"]
fights["split"] = assign_time_split(fights)
fights["drift_split"] = grouped_random_split(fights)

lines = ["# Phase 1: baselines and ceilings", "",
         "Generated by `scripts/run_baselines.py`. Test set not touched.", ""]
lines.append("## Split sizes")
lines.append("")
size = fights.groupby("split").agg(fights=("fid", "size"), first=("date", "min"), last=("date", "max"))
size["cards"] = cards.merge(fights[["fid", "split"]]).groupby("split").size()
size["cards_all_10_9"] = cards[cards.dev == 0].merge(fights[["fid", "split"]]).groupby("split").size()
lines.append(size.to_markdown())
lines.append("")

for split in ["train", "tune"]:
    require_test_unlock(split)
    f = fights[fights.split == split].fid
    c, r = cards[cards.fid.isin(f)], rounds[rounds.fid.isin(f)]
    table = []
    for name, rule in BASELINES.items():
        s = summarize(card_scores(c, r, rule(r)))
        s.insert(0, "method", name)
        table.append(s)
    s = summarize(ceiling_scores(c))
    s.insert(0, "method", "CEILING: most common card per fight")
    table.append(s)
    table = pd.concat(table)
    table = table[table.metric != "round_count_ll"]
    table["result"] = table.apply(lambda x: f"{x['mean']:.3f} [{x['lo']:.3f}, {x['hi']:.3f}]", axis=1)
    wide = table.pivot(index="method", columns="metric", values="result")
    wide = wide.loc[list(BASELINES) + ["CEILING: most common card per fight"]]
    lines += [f"## {split}", "", wide.to_markdown(), ""]

out = Path(__file__).resolve().parents[1] / "reports" / "phase1_baselines.md"
out.write_text("\n".join(lines))
print("\n".join(lines))
